all:
  children:
    proxmox:
      hosts:
        proxmox01:
          ansible_host: 10.13.104.218
          ansible_connection: local

    vms:
      hosts:
        vm01:
          vmid: 201
          vm_name: bestzige-vm-01
          ansible_host: 10.13.104.90
        vm02:
          vmid: 202
          vm_name: bestzige-vm-02
          ansible_host: 10.13.104.91
